export const defaultCards = [
  {
    id: 1,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
  {
    id: 2,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
  {
    id: 3,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
  {
    id: 4,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
  {
    id: 5,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
  {
    id: 6,
    title: 'titulo',
    price: 50.48,
    quantity: 69,
    totalPrice: 3483.12,
    productLine: 'linha',
  },
]
